// <auto-generated />
namespace BackendAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeuser1121 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeuser1121));
        
        string IMigrationMetadata.Id
        {
            get { return "201812271021476_changeuser11.21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
